name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: ${{ github.event_name != 'pull_request' || github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Check for Vite installation
        run: npm list vite

      - name: Build React and Vite
        run: npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Update Composer dependencies
        run: composer update --no-dev --optimize-autoloader

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy Files to the Build Directory
        run: |
          mkdir -p build/storage  # Create the storage directory
          cp -r public/* build/
          cp -r storage/* build/storage/

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: 'build'  # Ensure this points to your build directory containing index.html
          deployment_action: 'upload'  # Specify a valid action
          #api_location: 'api'  # If you have an API directory
          # output_location: ''  Optional, only if you need a specific output location
